### PR TITLE
Added missing links for the dependencies

### PR DESCRIPTION
**Pull request by plexx-dev**
Hello,
I noticed that your dependencies were missing links, so I've added them.

### CODE REVIEW

**Comment by Weckyy702** [comment]
Looking good :)

Gonna have to check the travis logs tho :monocle_face:

**Comment by Weckyy702** [comment]
:skull:

**Comment by plexx-dev** [comment]
I hope you like it 👨🏼‍🦰

**Comment by Weckyy702** [comment]
nah i dont :skunk:

**Comment by plexx-dev** [comment]
💀

**Pull request closed without merging**
